---
title: "POLE Remark Criteria - Additional Analysis"
output:
  html_document:
    css: ~/custom.css
  pdf_document: default
  word_document: default
---


```{r Preamble, message=FALSE,echo=FALSE,warning=FALSE,results='hide'}
# markdown manual: http://rmarkdown.rstudio.com/authoring_basics.html
rm(list=ls(all=TRUE)) #Clean up
```

```{r input_constants,message=FALSE,echo=FALSE,results='hide',warning=FALSE}
RUN.IN.MARKDOWN=TRUE # a flag to indicate that the codes are called from this markdown file
options(encoding = "UTF-8")
LIB.DIR <- "R_scripts/"
SETUP_KNITR.R <- paste(LIB.DIR,"SetUp_knitr.R",sep="")
DEFINEEVENTDATE.R <- paste(LIB.DIR,"DefineEventDate.R",sep="")
ED.CSV <- "data/endometrial_n518_2015-05-21.csv"
SETUP_DB.R <- "SetUp_db.R"
DATE.FORMAT="%m/%d/%Y" # this should be R's default date format
CASE.SELECTION.FLOW.CHART <- "images/remark.png" # CANNOT TAKE SPACE IN FILE PATH!!!!
DO.CITATIONS=FALSE

options(scipen=999) # disable scientific notation e.g. instead of 1x10E-3, show 0.001
```


```{r loadnMunge,message=FALSE,echo=FALSE,results='hide',warning=FALSE}
source(SETUP_KNITR.R)
source(DEFINEEVENTDATE.R)
source(SETUP_DB.R) # setup database ... e.g. censoring, remove cases

```


